# Introduction

## Course aims

Students will

* gain a general understanding of migration, its causes and consequences
* understand the functions of bird migration and its implications for population dynamics and ecological communities
* apply or get introduced to some frequently used ornithological field methods 
* interpret information from various data sources (e.g. observations, mark-recapture, data loggers, tracking methods, blood samples, genetics) and evaluate their representativeness and accuracy
* identify the more common European migrating bird species


For the **conceptual background**, we will cover the following aspects:

* Morphological and physiological adaptation to flight 
* Life cycle of birds (breeding, post-fledging, molting, migration, staging)
* Ecology and evolution of bird migration
* Timing of migration
* Migration strategies and orientation
* Global change and migration


For **practical and field methods**, we will introduce some of the most important field methods: 

* counting and identifying migrating birds, 
* bird catching and marking, 
* morphological and physiological measurements,
* tracking birds


**Student projects** are ideally conducted in groups of 2-4 persons. We expect students to choose a project during the first two days of the course (see list of potential projects \@ref(Sec:StudentProjects)). There are several slots for work on these projects over the course week and we expect students to give a brief (approx. 20 min) presentation on Friday, detailing the ecological question behind the project, the analytical approach chosen, the results obtained and a discussion. 
Within the student projects, we will introduce and apply important **theoretical approaches and analytical methods**


## Course schedule

The course consists of lectures, project work and excursions.

### Prepatory days 1 & 2: Tuesday, 5-6 September 2023 in Sempach (or online)


### Course day 1: Tuesday, 5 September 2023

* 9:30 - 11:00 Welcome and Introduction
Location: [Room Aquila at the Swiss Ornithological Institute, Seerose 1, 6204 Sempach](https://www.vogelwarte.ch/de/besuch/anreise). Note that we are in the red office building (not in the brown visitor centre).  

  + Introduction of all
  + Overview of the course aims and content
  + Student expectations from the course
  + What we expect from you and your projects
  + Ask us anything!
  
* 11:00 Lecture 1: Introduction to animal migration (SB)

* 12:00 - 13:30 Lunch break

* 13:30 Lecture 2: Characteristics of birds and introduction to expected species (FK)

* 14:30 Overview of student projects and papers to be read (information SB, FK)

* 15:15 Introduction to bird watching & bird identification
  + The 20 most common bird species at Col de Bretolet in September (Lecture & practice, FK, SB)  
  + brief practical (weather dependent): Walk along lakeshore to station and watch birds


### Course day 2: Wednesday, 6 September 2023 in Sempach
Location: [Room Aquila at the Swiss Ornithological Institute, Seerose 1, 6204 Sempach](https://www.vogelwarte.ch/de/besuch/anreise). Note that we are in the red office building (not in the brown visitor centre). 

* 9:30 – 10:30 Preparations project work (find your partner, search literature, install R-packages) (SB, FK)

* 10:30 – 12:00: Lecture 3: Modelling bird migration (lecture & practical, SB)
 + State-dependent migration models
   -	Basic ingredients and principles of state-dependent models
   -	Backward- forward 
   -	Parameterisations
   -	Typical research questions
   -	Examples of applications of migration model

* 13:30 – 15:30: Lecture 4: A refresher on working with R, incl. linear regression (lecture & practical, FK)

* 15:45 - 17:00: Lecture 5: Introduction to analysing survival based on data of marked animals (lecture & practical, FK)



### Excursion to Col de Bretolet: Mon-Fri 11-15 September 2023

The schedule of lectures, excursions and project work in Barmaz will be kept flexible as
we need to take weather conditions into account and may need to re-adjust.

### Course day 3: Monday, 11 September 2023

* Morning/ early afternoon: Travel to Barmaz (detailed travel suggestions will be provided separately)

* Afternoon:

* Lecture 6: Methods for studying animal migration (SB)
   + Moon-watching
   + Satellite telemetry
   + GPS loggers
   + Geolocators
   + Multi-sensor logger
   + Radar
   
   
* Lecture 7: Migration in the life-cycle of a bird (FK)

* Presentations & discussion of 'homework' papers
  + Give a brief overview of overarching questions addressed in the paper
  + Provide background to approach used 
  + Show/Explain main results
  + Discuss 


### Course day 4: Tuesday, 12 September 2023


* Morning: Hike to field station at Col de Bretolet
  + Field methods
  + Data 


* Afternoon 

* Lecture 8: Timing of migration (SB)
* Lecture 9: Orientation (FK)

* Project work



### Course day 5: Wednesday, 13 September 2023

* Morning: Hike to field station at Col de Bretolet
  + Field methods
  + Data 

* Afternoon
* Continue project work 

* Lecture 10: Climate change and other threats to migrating animals (SB)


### Course day 6: Thursday, 14 September 2023

* Morning: Hike to field station at Col de Bretolet (optional)
 
* Continue project work 
* Prepare final presentation

* Lecture 11: Climate change and other threats to Swiss breeding birds (FK)



### Course day 7: Friday, 15 September 2023

* Morning
  + Presentations of project work
  + Summary of course & take Home Message (FK & SB)
  + Student feedback

* Around noon - return home




## Preparations

To start the project work, we will ask students to read at least two papers - one general paper and one specific research paper and to introduce the key messages of these papers to your fellow students in the first days in the field (for guidelines to reading and summarizing papers, see Chapter Student's projects. 
The specific paper may be chosen to fit the topic of the project work (see also specific recommendations at the project descriptions). 


**General papers, reviews, synthesis**

- [@Bauer.2014] - Synthesis of how migratory animals influence community structure and ecosystem functioning 
- [@Bauer2017] - Services and disservices or (aerial) migrants
- [@Muheim.2014] - sensory orientation & navigation  
- [@Webster.2002] - migratory connectivity  
- [@Alerstam1998] - Migration strategies, bird migration theory  
- [@Alerstam2011] - Migration strategies of birds and insects compared  
- [@Knudsen2011] - Climate change and bird migration
- [@Runge2014] - Conservation of mobile species   
- [@Chapman2015a] - insect migration review  
- [@Runge2015] - global conservation of migratory birds  

**Specific research papers**

- [@Bauer2018] - modelling, human actions, management of migrant populations 
- [@Adamik2016] - geolocation, small birds, barrier crossing  
- [@Hu2016a] - insect migration, radar, quantification of migrants  
- [@LercheJrgensen.2018] - timing of migration & survival  
- [@Briedis2020] - broad-scale patterns of avian migration  
- [@Briedis2019] - Migration timing of male vs female birds  
- [@Tøttrup2012a] - spring and autumn migration strategies  
- [@Horton2020] - Climate change  influences on migration phenology
- [@Schmaljohann2017] - Climate change response of avian migrants
- [@Rosenberg2019] - Decline of avifauna
- [@Zuniga.2017] Survival of migrants and resident blackbirds  
- [@Abrahms2019] - whale migration, memory versus perception-based migration  
- [@McLaren2018] - Influence of artificial light on bird migration
