# Field methods

##	Observations: visual, moonwatching, IR, radar
Visual observations or observations by infrared cameras or radar result in counts of birds at a given time at a given location. Often, some behavioral observations are also recorded, such as flight altitude, flight direction or the behaviour of a bird resting on the ground. The different observation techniques differ in their detection ranges and in the information they provide (Table \@ref(tab:obsmethods)).


```{r obsmethods, tidy=TRUE, echo=FALSE}
obs_methods <- data.frame(read.csv("tables/ObservationMethods.csv", h=T, sep=";"))

knitr::kable(obs_methods, caption = "\\label{tab:obsmethods}Characteristics of different observation methods. MTR is migration traffic rate (a standardized migration intensity)",
  format.args = list(width = 30),
  booktabs = TRUE)
```




Example studies of visual observations:  

- EuroBird Portal: Phenology of migratory species based on records of amateur ornithologists, [link](https://eurobirdportal.org/ebp/en/#home/HIRRUS/r52weeks/CUCCAN/r52weeks/).  
- Description of migration pattern of Marsh warbler *Acrocephalus palustris* to southern Africa [@DowsettLemaire.1987].  

Example studies of moon watching:  

- Broad front migration and the Alps as an obstacle [@Liechti.1996b].  

Example studies of infrared observations:  

- Quantification of reverse migration in southern Sweden [@Zehnder.2002].  

Example radar studies:  

- Flight directions of migrating passerines along the autumn migration route [@Liechti.2012].

- Passerines migrating across the Sahara fly at night and land for the day [@Schmaljohann.2007].


##	Marking and reencountering
Marking birds in order to find out how far and where they move has been started by the Danish Hans Christian Cornelius Mortensen (1856 – 1921). In 1899 he, for the first time, marked Starlings *Sturnus vulgaris* with aluminium rings that were uniquely numbered and contained an address to make a potential finder reporting the ring [@Mortensen.1901]. Motivated by the success of Mortensen, the first ringing station was initiated in Rossiten (today Rybachi) on the Kurische Nehrung in 1900. Shortly after, other ringing stations were started on Helgoland and in the UK.

Today, around 5 million birds are ringed annually at many ringing stations by professional and private ringers in Europe [@Balmer.2008]. The ring numbers are coordinated within the countries by the governments who normally delegate this job to ringing schemes. The European ringing schemes are connected within the [EURING society](https://www.euring.org). In regular meetings and workshops, methodological standards are developed and the EURING data base, a data pool of all marking and reencounter data, maintained. EURING also started the [EURING Analytical meeting](https://www.euring.org/meetings/analytical-meetings) that serves as a network of scientists developing statistical and mathematical tools for the analysis of mark-reencounter data.

The capturing and marking methods underly national policies. In Switzerland, only trained persons can apply for a permission for capturing and marking birds. 

Mark-reencounter data is widely used to estimate survival, population sizes, movement pattern, migratory connectivity, and stop-over durations. @DuFeu.2016 review the scientific achievements of bird ringing, present the aims and policies of the EURING data base and give perspectives of bird ringing. 

A central challenge in the interpretation of mark-reencounter data is the spatial and temporal heterogeneity of reencounter probability [@Perdeck.1977; @KornerNievergelt.2010b; @Thorup.2014]. Mark-recapture modelling techniques such as the Cormack-Jolly-Seber (CJS) model [@Cormack.1964; @Jolly.1965; @Seber.1965], the multi-state model [@Arnason.1972; @Arnason.1991] or mark-dead recovery model [@Brownie.1985], are seminal techniques that are nowadays widely applied and integrated in a variety of different ecological models. These models estimate reencounter probability and thereby account for its heterogeneity while interpreting mark-reencounter data.

Many countries published their mark reencounters in migration atlases, e.g. @Bnlkke.2006, and @Saurola.2013.  

Examples of quantifying migratory connectivity studies based on ring reencounters: 

-	Estimation of the proportions of some song bird species migrating to Africa [@Thorup.2009].  
-	Origin of Woodcocks hunted in France [@Bauthian.2007].  
-	Migratory connectivity of European Nightingales *Luscinia megarhynchos* [@KornerNievergelt.2012b]  
-	Migratory connectivity of European reed warblers *Acrocephalus scirpaceus* [@Prochazka.2016].  

For estimating survival, it makes a fundamental difference whether the marked animal is found dead or whether it is resighted or recaptured alive.  When it is found dead the time of death and thus the lifespan of the individual is known. If we assume that the probability that a dead animal is found and its mark reported is independent of its age, then annual survival estimates are straight foreward. For example, using dead recoveries of 8 different songbird species ringed in Denmark,   @LercheJrgensen.2018 found that early arriving long-distance migrants in spring have a lower survival compared to late arriving individuals whereas arrival date was not correlated with survival in short-distance migrants. Interestingly, female long distance migrants arrived in average at a date correlated with highest survival, whereas males arrived earlier thereby risking an increase in mortality.

When marked animals are recaptured and released alive or resighted, the exact time of death is not known but a minimum life-span is known. In order to estimates survival from such data, it is necessary to estimate recapture or resighting probability (reencounter probability). If reencounter probability is known we can estimate the probability that an individual is still alive dependent on the time after its last reencounter. The CJS model allows estimating both reencounter and (apparent) survival probability. However, because both dead individuals and individuals that emigrated from the study area can no longer be reencountered, the model cannot distinguish between emigration and death. Therefore, the "survival" estimates from mark-recapture/resighting data have to be interpreted as the probability that an individual stays in the study area and survives, the so called apparent survival. 

Example studies:  

- @Sillett.2002 estimated lower apparent survival during migration compared to the breeding and non-breeding periods in the Black-throated blue warbler *Dendroica caerulescens*.  
- In the central Apennine, female White-winged snowfinches *Montifringilla nivalis* disappear at a higher rate in years with warm and dry summers, whereas the apparent survival of males does not seem to depend on summer weather [@Strinella.2020].



##	Tracking individuals

The vision of being able to follow a migratory bird on a computer screen has become, at least for larger animals, reality by now. Geographic position, flight altitude and other variables can be measured within short time and related to individual characteristics.  

Two major principles exist for tacking devices. Archival tags store information on geographic position or anything else locally and the tracking device needs to be retrieved to access this information. In contrast, transmitters actively transmit information to a receiver such that data can be remotely downloaded (Table \@ref(tab:TrackTechnology)). The development of tracking devices is ongoing intensively. Devices become smaller, energy households more efficient, type of measurements more diverse and programming more flexible.  

Table: (\#tab:TrackTechnology) Characteristics of different tracking techniques. Adapted from @Robinson.2010.

Tag type   | Data          | Pros and cons        |  
:-------|:------------------|:------------------|
*Archival tags* |     |    | 
Geolocators | Light and time | +:light weight (0.5 - 1.5g), recapturing required;  -:data analyses complex, location estimate with large error range (equinox) | 
Multi-sensor loggers | light and time  temperature  pressure  activity | +:additional information such as flight height, activity, etc., combination of data for better location estimation;  -:recapturing necessary |
GPS loggers | GPS position  temperature  pressure  activity  salinity | +:huge amount of information, precise location information;  -:recapturing necessary, relatively heavy |
*Transmitters* |     |    | 
PTT tags, RFID Radio frequency identification | identification of an individual with a reader at a strategic place (nest, feeding site) | +:low cost, small and leight-weigt (sometimes implanted); -:readers are expensive, individual is registered only when it is close to the reader (data are often noisy) |
Radio telemetry, VHF very high frequency telemetry | identification of an individual by an antenna over short to medium long distances (0-ca. 20km) | +:remote data collection, can be very light (0.3g), precise location information; -:battery life limited for small transmitters, high effort for data collection |
Satellite telemetry, e.g. ARGOS | GPS position of individuals at any time anywhere on the globe | +:remote data collection via satellite over very long distances, almost no effort needed for data collection, precise location information; -:large weight, expensive |

The [Motus project](https://motus.org/) is a world wide radio telemetry collaboration. Antennas around the world register radio tagged animals and send the information to the researchers.

The [movebank data base](https://www.movebank.org) is collecting tracking data from different studies. Its aim is to foster collaboration between different researchers. Some of the data are even provided for free.

Example studies using geolocation: 

- Non-breeding areas of Barn swallows *Hirundo rustica* [@Liechti.2014].    
- Migration pattern in relation to ecological barriers: [@Hahn.2014b].  
-Effects of geolocation on behaviour and body condition: Geolocators that weighted more than 2.3% of the body mass of tracked bird negatively influenced return rates in waders [@Weiser.2016].  

Example studies using radio telemetry:  

- @Bachler.2006 estimated stop-over durations in an oasis of the Sahara using mark-resighting data and compared these estimates with stop-over durations measured using radio telemetry.  
- At an Alaskan stop-over site,@Schmaljohann.2013 studied the effect of fuel load and weather on stop-over duration of the Wheatear *Oenanthe oenanthe*.   
- The first animal that was tracked by radio telemetry was a Grizzly bear *Ursus horribilis* [@Craighead.1972].  

Example studies of satellite telemetry:  

- @Kjellen.1997 tracked two Ospreys *Pandion haliaetus* from the same breeding location. The two individuals used completely different migration routes. The technique is nowadays widely applied for the study of movement behaviour of larger birds.



##	Orientation experiments
@Kramer.1949 detected that migratory birds show a directional preference. This behaviour has widely been used to study bird orientation using orientation cages. @Emlen.1966 designed an orientation cage that is still in use, the so-called "Emlen-funnel". Originally, ink was used to visualize the birds tracks. The ink was replaced by typewriter paper on which birds leave scratches while their feathers stayed clean. Some methodological issues with this type of orientation cage are discussed by @Nievergelt.2000. After typewriter paper has no longer been produced it was recently replaced by thermal paper [@Mouritsen.2009]. Automatic registration of bird activity reduces the amount of work for data collection, e.g. @Mouritsen.2001 or @Beck.1983.   

##	Stable isotopes, genetics and physiology
Stable isotopes indicate humidity and reflect trophic levels of the diet during the time when the bird’s feathers grew. In America, the isotopic map shows a north-south gradient [@Hobson.2008]. @Hobson.2012b developed a isotopic map for Africa that may serve as a basis for studying bird migration and non-breeding ecology. However, geographic information in isotopes is weak. Isotopes measure chemical composition of the diet and may better be interpreted as such [@Hahn.2013]. For extracting geographic information, often additional data is needed. For example, @Prochazka.2013 combined ring reencounters with isotopes to describe a migratory divide in the Reed warbler *Acrocephalus scirpaceus*. 

When populations differ genetically, the DNA of individuals at stop over or non-breeding sites can reveal their breeding origins. 
The analysis of mtDNA showed that Dunlins *Calidris alpina* observed in Portugal during migration originated from Greenland, Iceland and the Baltic Sea whereas the ones staying over winter had haplotypes of populations further to the east [@Lopes.2006]. 

The study of metabolites in blood samples revealed that birds use lipids and proteins as energy fuel for endurance flights. In a review, @JenniEiermann.2012 describe how the proportion of protein used is related to the duration of fastening, such as during a long migratory flight. 

## References
