# Migration models {#Sec:MigModels}

A variety of modelling approaches exist that investigate entire migrations or parts of it: simple analytical models, game-theoretic models, dynamic optimisation models (also known as stochastic dynamic pro-gramming models, SDP), individual-(or agent) based models (IBM), physical transport models, models based on evolutionary programming, network models and others. These models should not be con-fused with statistical analyses of migration, which may also yield predictive models but are not based on (assumed or hypothesised) mechanisms underlying migration. The models differ in their level of complexity and the assumptions they make, and the choice of a particular modelling approach should always be guided by the scientific questions that need to be tackled. For instance, to identify the rea-sons why birds migrate at night, a very general conceptual model is best suited (see below) while for specific predictions of the distribution of a migratory population, a spatio-temporally explicit approach will be required. 

Examples for models that aim at explaining specific migration behaviours and/or patterns are:
-	Kokko et al. (2006) explored reasons for the earlier arrival of males in the breeding area ob-served in many migratory bird species. They found that territoriality cannot explain this protan-dry because this affects both males and females. However, if early arriving males can increase their chance of mating whereas females cannot, arrival time of only males advanced.
-	Alerstam & Hedenström – The development of bird migration theory – which factor – time, en-ergy or safety determines migration patterns? (Alerstam & Hedenström 1998)
-	Alerstam – why do birds fly detours (Alerstam 2001)?
-	Hein – what determines maximum migration distance (Hein et al. 2012)?


In the following, we specifically introduce state-dependent migration models as they are a good trade-off between ‘conceptual’ and ‘realistic’ and may thus be used to investigate a variety of both fundamen-tal and applied ecological questions.

## State-dependent migration models
State-dependent optimality models calculate fitness-maximizing decisions depending on time, and a set of state-variables – in our case, location and body reserves. They use an optimization procedure (line-ar programming) that starts at the final time-point and calculates backwards the sequence of behav-ioural decision that would maximize fitness. 
The fundamental behavioural decisions a bird faces in each time-step in the model are a) to stay at its present location or b) to migrate to one of the following sites – each of which has consequences on the animal’s state (body reserves and location). Staying at the present location may allow foraging and accumulating fuel stores that are required for covering the next migratory step or for accumulating re-serves required for breeding. However, staying and foraging also entails mortality risks – as carrying body reserves may be costly and foraging may reduce vigilance (see below), and a time-cost when staying beyond the best time for arrival at the breeding grounds. Alternatively, flying to one of the fol-lowing sites may bring a bird closer to its breeding grounds and thus, facilitate arrival at the breeding grounds within the short time-window that allows successful breeding. However, if this ‘target-site’ does not provide food yet, staying there might increase starvation risk.   
Once the optimal decisions have been calculated for all possible combinations of time, body reserve levels and for all locations, forward simulations are run to generate predictions on individual birds dur-ing their journey from the wintering to breeding grounds. 

Data requirements. For model parameterisation, internal and external constraints (e.g. the costs of locomotion and food availability for all stopover sites) need to be known as well as how these change the values of state variables (e.g. how food availability affects body stores). Model predictions are ide-ally scrutinized by spatio-temporal explicit data of the population along the migratory route (e.g. count data) or individual migration data from tracking studies. 
Elaborate background and methodology on state-dependent models can be found in the excellent text-books of (Houston & McNamara 1999, Clark & Mangel 2000).
State-dependent migration models have been used for a variety of questions; a few examples are the following:
•	Estimating the impact of global changes on stop-over site use (Bauer et al. 2008).
•	Managing migrant populations at lowest economic cost  (Klaassen et al. 2008a). 
•	Hunting migratory populations
•	Potential reasons for why red knots (Calidris canutus) use multiple routes to their breeding grounds (Bauer et al. 2010)
•	Besides birds, SDP models have also investigated the spawning migrations of cod assuming optimal energy allocations (Jørgensen & Fiksen 2006, Jørgensen et al. 2008). 




## References
