# Exercise: Timing {#exctiming}

## Arrival dates in spring


Arrival of migratory birds in central Europe in spring varies among years. In this exercise, explore dates of first observations of the species in central Europe.


Two data sets are available: 

1. Data provided by the authors of @Strebel2014. These data include first observation dates of selected bird species in Switzerland over around 10 years (~2000 - 2012). The data estimates detectability peaks and discusses how observer bias influences first arrival dates in citizen science data.  

2. ebird data is a citizen science data set that provides - depending on the species data over longer time periods for any place on the world.    

Choose a data set from either 1) or 2), choose a species and describe how the timing of the first observation has changed over the years. Use regression analyses.  



```{r, eval=FALSE}

# data download https://datadryad.org/dataset/doi:10.5061/dryad.k20q2  (source: https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12175)

# extract first observation per species and year:
library(dplyr)
first_obs <- obs_data %>%
  group_by(Year, ArtId) %>%
  summarise(first_day = min(DayOfYear), .groups = "drop")




```


 


```{r. eval=FALSE}
# How to download and filter ebird data

#Go to: https://ebird.org/data/download
#Request the full EBD or a regional subset (e.g., a country or state).

library(auk)
library(tidyverse)

# Path to the downloaded EBD file
ebd_file <- "path/to/ebd_relFeb-2024.txt"
sampling_file <- "path/to/ebd_sampling_relFeb-2024.txt"

# Define filters
species <- "Northern Cardinal"
region <- "US-NY"  # New York, USA
start_date <- "2021-05-01"
end_date <- "2021-05-31"


# Create an auk_ebd object and apply filters
ebd_filtered <- auk_ebd(ebd_file, sampling_file) %>%
  auk_species(species) %>%
  auk_country("United States") %>%
  auk_state("New York") %>%
  auk_date(start_date, end_date)

# Output file
output_file <- "filtered_ebd.txt"

# Run the filter
auk_filter(ebd_filtered, file = output_file)


```

