# Seminar: Ecosystem Effects of Migrants {#SemEcosystem}

As you have heard in the lecture, migratory animals can influence important
community processes and ecosystem functions. 
To this end, we'll look at some recent works and discuss what their findings mean.

Let's first discuss in class and compile which processes would be important to consider.


Work in groups on compiling evidence (or not) of migrants influencing ecosystem
processes and community dynamics.

Have a read of the general reasoning and major results of the following papers 
(not details). 

 - Wildebeest in Serengeti [link](https://www.pnas.org/doi/10.1073/pnas.1614778114)
 - Insects in UK/Europe [link](https://www.science.org/doi/10.1126/science.aah4379)
 - Migrants in Arctic food web [link](https://www.frontiersin.org/journals/ecology-and-evolution/articles/10.3389/fevo.2022.1077260/full)
 - Pacific salmon [link](https://www.nature.com/articles/s41586-024-07980-2)
 - North-American Bison [link](https://www.science.org/doi/10.1126/science.adu0703)

Think about the following questions:
 - What (which factors & processes) do migratory animals change in resident communities?
 - Is it a relevant process/factor, e.g. compared to similar processes?
 - How does the food web/ community/ ecosystem look like without migratory animals? 
 - Which effect do you think will the seasonal appearance/ disappearance of migrants have?
 - How do the migrant-effects differ between larger/smalelr food webs? 



